title: Alaria Dynamics
email: info@alariadynamics.co
description: "Advanced aerospace & defense systems — Alaria Dynamics"
# When GitHub Pages serves your site under a project page like
# https://prinsessakyti.github.io/alariadynamics.co/ set `url` to your
# user pages host and `baseurl` to the repository name.
baseurl: "/alariadynamics.co"
url: "https://prinsessakyti.github.io"
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

collections:
  products:
    output: true

permalink: pretty
